# Generated by Django 5.2.3 on 2025-06-28 06:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_skill_profile"),
    ]

    operations = [
        migrations.CreateModel(
            name="MatchRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "mentee",
                    models.ForeignKey(
                        limit_choices_to={"role": "mentee"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outgoing_match_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "mentor",
                    models.ForeignKey(
                        limit_choices_to={"role": "mentor"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incoming_match_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("mentor", "mentee")},
            },
        ),
    ]
